"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationTrigger = exports.LocationStatus = exports.LoadStatus = exports.XPathResult = exports.WebsocketResource = exports.Resource = exports.Tab = exports.FrameEnvironment = exports.Node = exports.BlockedResourceType = exports.KeyboardKey = exports.ResourceType = exports.MouseButton = exports.InteractionCommand = exports.ConnectionToHeroCore = exports.Command = exports.DetachedElement = exports.HeroReplay = void 0;
// setup must go first
require("./lib/SetupAwaitedHandler");
require("./lib/DomExtender");
const ITabOptions_1 = require("@ulixee/hero-interfaces/ITabOptions");
Object.defineProperty(exports, "BlockedResourceType", { enumerable: true, get: function () { return ITabOptions_1.BlockedResourceType; } });
const IKeyboardLayoutUS_1 = require("@ulixee/unblocked-specification/agent/interact/IKeyboardLayoutUS");
Object.defineProperty(exports, "KeyboardKey", { enumerable: true, get: function () { return IKeyboardLayoutUS_1.KeyboardKey; } });
const IResourceType_1 = require("@ulixee/unblocked-specification/agent/net/IResourceType");
Object.defineProperty(exports, "ResourceType", { enumerable: true, get: function () { return IResourceType_1.ResourceType; } });
const IInteractions_1 = require("@ulixee/unblocked-specification/agent/interact/IInteractions");
Object.defineProperty(exports, "InteractionCommand", { enumerable: true, get: function () { return IInteractions_1.InteractionCommand; } });
Object.defineProperty(exports, "MouseButton", { enumerable: true, get: function () { return IInteractions_1.MouseButton; } });
const AwaitedDom_1 = require("@ulixee/hero-interfaces/AwaitedDom");
Object.defineProperty(exports, "Node", { enumerable: true, get: function () { return AwaitedDom_1.Node; } });
Object.defineProperty(exports, "XPathResult", { enumerable: true, get: function () { return AwaitedDom_1.XPathResult; } });
const Location_1 = require("@ulixee/unblocked-specification/agent/browser/Location");
Object.defineProperty(exports, "LoadStatus", { enumerable: true, get: function () { return Location_1.LoadStatus; } });
Object.defineProperty(exports, "LocationStatus", { enumerable: true, get: function () { return Location_1.LocationStatus; } });
Object.defineProperty(exports, "LocationTrigger", { enumerable: true, get: function () { return Location_1.LocationTrigger; } });
const IInteractions_2 = require("./interfaces/IInteractions");
Object.defineProperty(exports, "Command", { enumerable: true, get: function () { return IInteractions_2.Command; } });
const extendables_1 = require("./lib/extendables");
Object.defineProperty(exports, "HeroReplay", { enumerable: true, get: function () { return extendables_1.HeroReplay; } });
Object.defineProperty(exports, "FrameEnvironment", { enumerable: true, get: function () { return extendables_1.FrameEnvironment; } });
Object.defineProperty(exports, "Tab", { enumerable: true, get: function () { return extendables_1.Tab; } });
Object.defineProperty(exports, "Resource", { enumerable: true, get: function () { return extendables_1.Resource; } });
Object.defineProperty(exports, "WebsocketResource", { enumerable: true, get: function () { return extendables_1.WebsocketResource; } });
const ConnectionToHeroCore_1 = require("./connections/ConnectionToHeroCore");
exports.ConnectionToHeroCore = ConnectionToHeroCore_1.default;
const DetachedElement_1 = require("./lib/DetachedElement");
exports.DetachedElement = DetachedElement_1.default;
require("./env");
exports.default = extendables_1.Hero;
//# sourceMappingURL=index.js.map