module.exports = {
  verbose: false,
  testMatch: ['**/test/*.test.js'],
  testEnvironment: 'node',
  collectCoverage: false,
  collectCoverageFrom: [
    'client/**/*.{js}',
    'core/**/*.{js}',
    'core-server/**/*.{js}',
    'emulators/**/*.{js}',
    'emulator-plugins/**/*.{js}',
    'full-client/**/*.{js}',
    'humanoids/**/*.{js}',
    'mitm/**/*.{js}',
    'remote-client/**/*.{js}',
    'replay-api/**/*.{js}',
    'session-state/**/*.{js}',
    'commons/**/*.{js}',
  ],
  coveragePathIgnorePatterns: ['index.js'],
  modulePathIgnorePatterns: ['config'],
  globalTeardown: './jest.teardown.js',
  globalSetup: './jest.setup.js',
  testTimeout: 20e3,
  reporters: [
    'default',
    [
      'jest-summary-reporter',
      {
        failuresOnly: true,
      },
    ],
    'jest-junit'
  ],
  roots: [
    'client/',
    'core/',
    'core-server/',
    'emulators/',
    'emulator-plugins/',
    'full-client/',
    'humanoids/',
    'humanoid-plugins/',
    'mitm/',
    'remote-client/',
    'replay-api/',
    'session-state/',
    'commons/',
  ],
  moduleDirectories: [
    'node_modules',
    'client/node_modules',
    'core/node_modules',
    'core-server/node_modules',
    'emulators/node_modules',
    'full-client/node_modules',
    'humanoids/node_modules',
    'mitm/node_modules',
    'remote-client/node_modules',
    'replay-api/**/node_modules',
    'session-state/**/node_modules',
    'commons/**/node_modules',
  ],
};
