import ITheme from '~shared/interfaces/ITheme';
import { BLUE_500 } from './colors';

export const lightTheme: ITheme = {
  titlebarBackgroundColor: '#d4d4d4',
  addressBarBackgroundColor: '#fff',
  addressBarTextColor: '#000',
  toolbarBackgroundColor: '#ECECEC',
  toolbarBottomLineBackgroundColor: 'rgba(0, 0, 0, 0.12)',
  toolbarLightForeground: false,
  toolbarSeparatorColor: 'rgba(0, 0, 0, 0.12)',
  controlBackgroundColor: 'rgba(0,0,0,0.08)',
  controlHoverBackgroundColor: 'rgba(0, 0, 0, 0.1)',
  controlValueColor: '#000',
  controlLightIcon: false,
  switchBackgroundColor: 'rgba(0, 0, 0, 0.16)',
  dialogBackgroundColor: '#fff',
  dialogSeparatorColor: 'rgba(0, 0, 0, 0.12)',
  dialogTextColor: '#000',
  dialogLightForeground: false,
  pagesBackgroundColor: '#fff',
  pagesLightForeground: false,
  pagesTextColor: '#000',
  pagesNavigationDrawerBackgroundColor: '#fafafa',
  dropdownBackgroundColor: '#fff',
  dropdownBackgroundColorTranslucent: 'rgba(255, 255, 255, 0.7)',
  dropdownSeparatorColor: 'rgba(0, 0, 0, 0.12)',
  backgroundColor: '#fff',
  accentColor: BLUE_500,
};

export const darkTheme: ITheme = {
  titlebarBackgroundColor: '#1c1c1c',
  addressBarBackgroundColor: '#262626',
  addressBarTextColor: '#fff',
  toolbarBackgroundColor: '#333333',
  toolbarBottomLineBackgroundColor: 'rgba(255, 255, 255, 0.08)',
  toolbarLightForeground: true,
  toolbarSeparatorColor: 'rgba(255, 255, 255, 0.12)',
  controlBackgroundColor: 'rgba(255, 255, 255, 0.1)',
  controlHoverBackgroundColor: 'rgba(255, 255, 255, 0.12)',
  controlValueColor: '#fff',
  controlLightIcon: true,
  switchBackgroundColor: 'rgba(255, 255, 255, 0.24)',
  dialogBackgroundColor: '#383838',
  dialogSeparatorColor: 'rgba(255, 255, 255, 0.12)',
  dialogTextColor: '#fff',
  dialogLightForeground: true,
  pagesBackgroundColor: '#212121',
  pagesLightForeground: true,
  pagesTextColor: '#fff',
  dropdownBackgroundColor: 'rgb(66, 66, 66)',
  dropdownBackgroundColorTranslucent: 'rgb(60, 60, 60, 0.6)',
  dropdownSeparatorColor: 'rgba(255, 255, 255, 0.12)',
  pagesNavigationDrawerBackgroundColor: 'rgba(255, 255, 255, 0.05)',
  backgroundColor: '#1c1c1c',
  accentColor: BLUE_500,
};
