import IEmulationProfile from '@ulixee/unblocked-specification/plugin/IEmulationProfile';
import IUnblockedPlugins from '@ulixee/unblocked-specification/plugin/IUnblockedPlugins';
import IUnblockedPlugin, { IUnblockedPluginClass, PluginConfigs } from '@ulixee/unblocked-specification/plugin/IUnblockedPlugin';
import { URL } from 'url';
import { IInteractionGroups, IInteractionStep } from '@ulixee/unblocked-specification/agent/interact/IInteractions';
import IInteractionsHelper from '@ulixee/unblocked-specification/agent/interact/IInteractionsHelper';
import IHttpResourceLoadDetails from '@ulixee/unblocked-specification/agent/net/IHttpResourceLoadDetails';
import IHttp2ConnectSettings from '@ulixee/unblocked-specification/agent/net/IHttp2ConnectSettings';
import IBrowserContext from '@ulixee/unblocked-specification/agent/browser/IBrowserContext';
import { IWorker } from '@ulixee/unblocked-specification/agent/browser/IWorker';
import { IPage } from '@ulixee/unblocked-specification/agent/browser/IPage';
import IBrowser from '@ulixee/unblocked-specification/agent/browser/IBrowser';
import IBrowserUserConfig from '@ulixee/unblocked-specification/agent/browser/IBrowserUserConfig';
import IHttpSocketAgent from '@ulixee/unblocked-specification/agent/net/IHttpSocketAgent';
import ITlsSettings from '@ulixee/unblocked-specification/agent/net/ITlsSettings';
import ITcpSettings from '@ulixee/unblocked-specification/agent/net/ITcpSettings';
import IDnsSettings from '@ulixee/unblocked-specification/agent/net/IDnsSettings';
import IPoint from '@ulixee/unblocked-specification/agent/browser/IPoint';
import IDevtoolsSession from '@ulixee/unblocked-specification/agent/browser/IDevtoolsSession';
import { IHooksProvider } from '@ulixee/unblocked-specification/agent/hooks/IHooks';
import { IFrame } from '@ulixee/unblocked-specification/agent/browser/IFrame';
import IResourceType from '@ulixee/unblocked-specification/agent/net/IResourceType';
export default class Plugins implements IUnblockedPlugins {
    profile: IEmulationProfile;
    isStarted: boolean;
    get hasHooks(): boolean;
    readonly instances: IUnblockedPlugin[];
    private hooksByName;
    constructor(emulationProfile: IEmulationProfile, pluginClasses: IUnblockedPluginClass[], pluginConfigs?: PluginConfigs);
    hook(hooksToAdd: IHooksProvider, runConfigure?: boolean): void;
    onClose(): void;
    addDomOverride(runOn: 'page' | 'worker', script: string, args: Record<string, any> & {
        callbackName?: string;
    }, callback?: (data: string, frame: IFrame) => any): boolean;
    playInteractions(interactionGroups: IInteractionGroups, runFn: (interaction: IInteractionStep) => Promise<void>, helper: IInteractionsHelper): Promise<void>;
    adjustStartingMousePoint(point: IPoint, helper: IInteractionsHelper): Promise<void>;
    configure(profile: IEmulationProfile): Promise<void>;
    onNewBrowser(browser: IBrowser, launchArgs: IBrowserUserConfig): Promise<void>;
    onNewPage(page: IPage): Promise<void>;
    onNewFrameProcess(frame: IFrame): Promise<any>;
    onNewWorker(worker: IWorker): Promise<void>;
    onNewBrowserContext(context: IBrowserContext): Promise<void>;
    onDevtoolsPanelAttached(devtoolsSession: IDevtoolsSession): Promise<any>;
    onDevtoolsPanelDetached(devtoolsSession: IDevtoolsSession): Promise<any>;
    onDnsConfiguration(settings: IDnsSettings): void;
    onTcpConfiguration(settings: ITcpSettings): void;
    onTlsConfiguration(settings: ITlsSettings): void;
    onHttpAgentInitialized(agent: IHttpSocketAgent): Promise<void>;
    onHttp2SessionConnect(resource: IHttpResourceLoadDetails, settings: IHttp2ConnectSettings): Promise<void>;
    shouldBlockRequest(url: string, resourceTypeIfKnown?: IResourceType): boolean;
    beforeHttpRequest(resource: IHttpResourceLoadDetails): Promise<void>;
    beforeHttpRequestBody(resource: IHttpResourceLoadDetails): Promise<void>;
    beforeHttpResponse(resource: IHttpResourceLoadDetails): Promise<any>;
    beforeHttpResponseBody(resource: IHttpResourceLoadDetails): Promise<void>;
    afterHttpResponse(resource: IHttpResourceLoadDetails): Promise<any>;
    websiteHasFirstPartyInteraction(url: URL): void;
}
