export const DEFAULT_TAB_MARGIN_TOP = 4;

export const DEFAULT_TAB_HEIGHT = 32;

// Toolbar
export const TOOLBAR_HEIGHT = 42;

export const TOOLBAR_BUTTON_WIDTH = 36;
export const TOOLBAR_BUTTON_HEIGHT = 32;

export const ADD_TAB_BUTTON_WIDTH = 28;
export const ADD_TAB_BUTTON_HEIGHT = 28;

export const DEFAULT_TITLEBAR_HEIGHT = DEFAULT_TAB_MARGIN_TOP + DEFAULT_TAB_HEIGHT;

export const VIEW_Y_OFFSET = TOOLBAR_HEIGHT + DEFAULT_TITLEBAR_HEIGHT;

// Dialogs
export const DIALOG_MARGIN = 16;
export const DIALOG_MARGIN_TOP = 3;
