"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Command = void 0;
var Command;
(function (Command) {
    Command["scroll"] = "scroll";
    Command["move"] = "move";
    Command["click"] = "click";
    Command["clickLeft"] = "clickLeft";
    Command["clickMiddle"] = "clickMiddle";
    Command["clickRight"] = "clickRight";
    Command["clickDown"] = "clickDown";
    Command["clickDownLeft"] = "clickDownLeft";
    Command["clickDownMiddle"] = "clickDownMiddle";
    Command["clickDownRight"] = "clickDownRight";
    Command["clickUp"] = "clickUp";
    Command["clickUpLeft"] = "clickUpLeft";
    Command["clickUpMiddle"] = "clickUpMiddle";
    Command["clickUpRight"] = "clickUpRight";
    Command["doubleclick"] = "doubleclick";
    Command["doubleclickLeft"] = "doubleclickLeft";
    Command["doubleclickMiddle"] = "doubleclickMiddle";
    Command["doubleclickRight"] = "doubleclickRight";
    Command["keyPress"] = "keyPress";
    Command["keyDown"] = "keyDown";
    Command["keyShortcut"] = "keyShortcut";
    Command["keyUp"] = "keyUp";
    Command["type"] = "type";
    Command["waitForMillis"] = "waitForMillis";
})(Command || (exports.Command = Command = {}));
//# sourceMappingURL=IInteractions.js.map